### ISSUE TITLE
menu freezes, not able to open menus after installing the theme

### ISSUE THREAD

**Issue by itsrickyhub** [AlexWebLab/bs5starter#1]
Hi, Alex, I am new to WordPress development, I am a beginner, I searched on internet for Bootstrap 5 navwalker and came to this profile, unfortunately given navwalker and theme both didn't work for me. It freezes if there is any dropdown item in navbar.

Can you update the code?
Thanks.

**Comment by AlexWebLab** [comment]
> Hi, Alex, I am new to WordPress development, I am a beginner, I searched on internet for Bootstrap 5 navwalker and came to this profile, unfortunately given navwalker and theme both didn't work for me. It freezes if there is any dropdown item in navbar.
> 
> Can you update the code?
> Thanks.

Can you please send me your code?

**Comment by itsrickyhub** [comment]
It's same as per this git. Only I installed the theme and created menus, when there is a child menu, it's not showing any dropdown and freezes up there. :(

**Comment by itsrickyhub** [comment]
It was some plugin conflict, solved, Thanks buddy :)

**Comment by itsrickyhub** [comment]
came to know, it's working if the parent menu is custom link i.e. with #, it's not working if there is a dropdown in parent category or parent page. Thanks :)

**Comment by AlexWebLab** [comment]
I'm glad to know that now it's working on your side and it was only a plugin issue.

> came to know, it's working if the parent menu is custom link i.e. with #, it's not working if there is a dropdown in parent category or parent page. Thanks :)

Yeah, in order to strictly follow the Bootstrap 5 navbar, the .dropdown-toggle href attribute MUST be "#", for other cases, it can be customised. There is a lot of debate online regarding this topic. I personally agree with Bootstrap choice. Peace!
